[package]
name = "asm-matcher"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Pizarro <gpizarro@javaman.net>"]
description = "Analyzes similarity between assembly functions"
repository = "https://github.com/TheNewJavaman/asm-matcher"
license = "MIT"

[dependencies]
